### ISSUE TITLE
Request to update project URL

### ISSUE THREAD

**Issue by atreyasha** [citp/PrivacyPoliciesOverTime#1]
Hi @rbamos,

Just wanted to update that we are moving our code base to GitHub. Could I ask you to update our repository's URL in the readme to the following:

https://github.com/infsys-lab/policy-classifier

Thanks and wishing you a nice day!

**Comment by rbamos** [comment]
Thanks Atreya, I sent you an email. Please respond to that so I can address this issue (side note: apologies, for some reason your last name is listed as your first name in my contact book)

**Comment by atreyasha** [comment]
Hi @rbamos. Responded via email.

**Comment by rbamos** [comment]
Confirmed and fixed. Thanks!
